gravatarsize: 50
length_activity:
  maximum: 140
perpage: 5
word:
  all_word: 0
  learned_word: 1
  not_learned_word: 2
  status:
    - All
    - Learned
    - Not Learned
lesson:
  lessonsize: 10
answers_number:
  - Answer 1
  - Answer 2
  - Answer 3
  - Answer 4
answers_number_size: 4
